{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "webapp1.serviceAccountName" . }}
  labels:
{{ include "webapp1.labels" . | indent 4 }}
{{- end -}}
