apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia2
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: fc
        image: luksa/kubia
        ports:
        - containerPort: 8080
