apiVersion: v1
kind: Pod
metadata:
  name: pod10
  labels:
    name: pod10
spec:
  containers:
  - name: pod10
    image: nginx:1.7.9
    envFrom:
      - secretRef:
          name: secret1
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
