# following three lines provide META-DATA for current object
apiVersion: v1  # k8s API version
kind: Pod       # Type pf OBJECT this file manages/deploys
metadata:
  name: pod2    # Unique name for this object
  labels:       # Optional labels (User defined key/value pairs)
    name: web1
  
# The actual object (POD) definition 
spec:
  containers:   # list of containers 
  # start of first container
  - name: web1  # name for container
    image: mahendrshinde/myweb:latest  # container image 
    # Optional resource contraints
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    # application port (nginx uses 80)
    ports:
      - containerPort: 80
    # start of second container
  - name: test
    image: busybox
    command: ['sh','-c','echo Hello World && sleep 3600']
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    