
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0-5
  labels:
    app: webapp
    release: "0-5"
spec:
  containers:
  - name: webapp
    image: shivamjha/kubernetes-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0
  labels:
    app: webapp
    release: "0"
spec:
  containers:
  - name: webapp
    image: shivamjha/kubernetes-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queue
    image: shivamjha/kubernetes-fleetman-queue:release1
