# To create the busybox pod to run commands from

apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    args:
    - sleep
    - "1000"
  #nodeSelector:
   # kubernetes.io/hostname: shivam2.labserver.com