apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
    release: "1"
spec:
  containers:
  - name: webapp
    image: shivamjha/k8s-fleetman-webapp-angular:release1

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-2
  labels:
    app: webapp
    release: "2"
spec:
  containers:
  - name: webapp
    image: shivamjha/k8s-fleetman-webapp-angular:release2
